// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST_Company.Models;

#nullable disable

namespace ST_Company.Migrations
{
    [DbContext(typeof(Company_Context))]
    partial class Company_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ST_Company.Models.Emp_Project", b =>
                {
                    b.Property<int>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("proj_id")
                        .HasColumnType("int");

                    b.Property<int?>("WorkingHours")
                        .HasColumnType("int");

                    b.HasKey("emp_id", "proj_id");

                    b.HasIndex("proj_id");

                    b.ToTable("EmpProjects");
                });

            modelBuilder.Entity("ST_Company.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Office_id")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Office_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ST_Company.Models.Office", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("ST_Company.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ST_Company.Models.Emp_Project", b =>
                {
                    b.HasOne("ST_Company.Models.Employee", "Employee")
                        .WithMany("emp_Projects")
                        .HasForeignKey("emp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ST_Company.Models.Project", "Project")
                        .WithMany("emp_Projects")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ST_Company.Models.Employee", b =>
                {
                    b.HasOne("ST_Company.Models.Office", "office")
                        .WithMany("Employees")
                        .HasForeignKey("Office_id");

                    b.Navigation("office");
                });

            modelBuilder.Entity("ST_Company.Models.Employee", b =>
                {
                    b.Navigation("emp_Projects");
                });

            modelBuilder.Entity("ST_Company.Models.Office", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ST_Company.Models.Project", b =>
                {
                    b.Navigation("emp_Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
